;;; Compiled snippets and support files for `math-mode'
;;; Snippet definitions:
;;;
(yas-define-snippets 'math-mode
		     '(("vecol" "\\left ( \\begin{array}{c} ${1:v_{1}} \\\\\\ ${2:v_{2}} \\end{array} \\right )$0" "vector-column" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/vector-column" nil nil)
		       ("vec" "\\vec{${1:x}}$0" "vector" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/vector" nil nil)
		       ("var" "\\(${1:x}\\)$0" "variable" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/variable" nil nil)
		       ("ul" "\\underline{${1:x}}$0" "underline" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/underline" nil nil)
		       ("unbr" "\\underbrace{$1}_{$2}$0" "underbrace" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/underbrace" nil nil)
		       ("tr" "\\text{Tr}\\left[ $1 \\right]$0" "trace" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/trace" nil nil)
		       ("til" "\\widetilde{${1:x}}$0" "tilde" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/tilde" nil nil)
		       ("thm" "#+begin_theorem\n$1\n#+end_theorem" "theorem" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/theorem" nil nil)
		       ("text" "\\text{${1:text}}$0" "text" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/text" nil nil)
		       ("tp" "\\otimes $0" "tensor-product" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/tensor-product" nil nil)
		       ("tan" "\\tan \\left( $1 \\right)$0" "tan" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/tan" nil nil)
		       ("suml" "\\sum\\limits_{${1:n}}$0" "sum-with-limits" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/sum-with-limits" nil nil)
		       ("se" "\\begin{subequations}\n\\begin{align}\n ${1:x=y}\n\\end{align}\n\\end{subequations} $0" "subequations" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/subequations" nil nil)
		       ("star" "\\star" "star" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/star" nil nil)
		       ("sq" "\\sqrt{${1:x}}$0" "square-root" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/square-root" nil nil)
		       ("\\[" "\\lbrack $1 \\rbrack$0" "square-brackets-2" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/square-brackets-2" nil nil)
		       ("[]" "\\left[ ${1:x} \\right] $0" "square-brackets" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/square-brackets" nil nil)
		       ("vv" "\\\\(${1:x}\\\\)$0" "single-variable" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/single-variable" nil nil)
		       ("sin" "\\sin \\left( $1 \\right)$0" "sine" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/sinee" nil nil)
		       ("ss" "[ $1 ]$0" "simple-square-brackets" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/simple-square-brackets" nil nil)
		       ("bb" "( $1 )$0" "simple-brackets" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/simple-brackets" nil nil)
		       ("set" "\\\\{ ${1:x} \\\\}$0" "set" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/set" nil nil)
		       ("arr" "\\rightarrow" "right-arrow" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/right-arrow" nil nil)
		       ("qci" "\\Qcircuit @C=1em @R=0.7em @!R {\n& ${1:x}\n} $0  " "qcircuit" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/qcircuit" nil nil)
		       ("Ps" "\\Psi$0" "Psi" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/psi_cap" nil nil)
		       ("ps" "\\psi$0" "psi" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/psi" nil nil)
		       ("proof" "#+begin_proof\n$1\n#+end_proof" "proof" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/proof" nil nil)
		       ("prodl" "\\prod\\limits_{$1} $0" "product-with-limits" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/product-with-limits" nil nil)
		       ("'" "^{\\prime}" "prime" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/prime" nil nil)
		       ("pi" "\\pi" "pi" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/pie" nil nil)
		       ("Pi" "\\Pi" "Pi" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/pi_cap" nil nil)
		       ("dl" "\\partial_{${1:\\mu}}$0" "partial_low" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/partial_low" nil nil)
		       ("du" "\\partial^{${1:\\mu}}$0" "partial_high" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/partial_high" nil nil)
		       ("pd" "\\frac{\\partial ${1:num}}{\\partial ${2:den}}$0 " "partial-derivative" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/partial-derivative" nil nil)
		       ("pa" "\\partial" "partial" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/partial" nil nil)
		       ("ol" "\\overline{${1:x}}$0" "overline" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/overline" nil nil)
		       ("obr" "\\overbrace{$1}^{$2}$0" "overbrace" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/overbrace" nil nil)
		       ("bar" "\\bar{$1}$0" "bar" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/overbar" nil nil)
		       ("n2" "\\left| ${1:x} \\right|^2$0" "norm-squared" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/norm-squared" nil nil)
		       ("multipart" "\\left\\\\{ \\begin{array}{ll}\n$1 & $2 \\\\\\\n$3 & $4\n\\end{array} \n\\right. $0\n" "multi-part" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/multi-part" nil nil)
		       ("mod" "\\left| $1 \\right|$0" "modulus" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/modulus" nil nil)
		       ("guu" "${1:g}^{${2:\\mu} ${3:\\nu}}$0" "metric_upper_upper" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/metric_upper_upper" nil nil)
		       ("gul" "${1:g}^{${2:\\mu}}_{${3:\\nu}}$0" "metric_upper_lower" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/metric_upper_lower" nil nil)
		       ("glu" "${1:g}_{${2:\\mu}}^{${3:\\nu}}$0" "metric_lower_upper" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/metric_lower_upper" nil nil)
		       ("gll" "${1:g}_{${2:\\mu} ${3:\\nu}}$0" "metric_lower_lower" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/metric_lower_lower" nil nil)
		       ("mat4" "\\left ( \\begin{array}{cccc} \n${1:x_{11}} & ${2:x_{12}} & ${3:x_{13}} & ${4:x_{14}}  \\\\\\\n${5:x_{21}} & ${6:x_{22}} & ${7:x_{23}} & ${8:x_{24}}  \\\\\\\n${9:x_{31}} & ${10:x_{32}} & ${11:x_{33}} & ${12:x_{34}} \\\\\\\n${13:x_{41}} & ${14:x_{42}} & ${15:x_{43}} & ${16:x_{44}} \\\\\\\n\\end{array} \\right ) $0\n" "matrix4by4" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/matrix4by4" nil nil)
		       ("mat3" "\\left ( \\begin{array}{ccc} \n${1:x_{11}} & ${2:x_{12}} & ${3:x_{13}} \\\\\\\n${4:x_{21}} & ${5:x_{22}} & ${6:x_{23}} \\\\\\\n${7:x_{31}} & ${8:x_{32}} & ${9:x_{33}} \\\\\\\n\\end{array} \\right ) $0" "matrix3by3" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/matrix3by3" nil nil)
		       ("mat2" "\\left ( \\begin{array}{cc} \n${1:x_{11}} & ${2:x_{12}} \\\\\\\n${3:x_{21}} & ${4:x_{22}}  \\end{array} \\right ) $0" "matrix2by2" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/matrix2by2" nil nil)
		       ("mcal" "\\mathcal{${1:x}} $0" "mathcal" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/mathcal" nil nil)
		       ("mbf" "\\mathbf{$1}$0" "mathbf" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/mathbf" nil nil)
		       ("mbb" "\\mathbb{${1:R}}$0" "mathbb" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/mathbb" nil nil)
		       ("vb" "\\mathbf{${1:x}}$0" "math bold" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/math_bold" nil nil)
		       ("xx" "\\[ ${1:x} \\]$0" "math-mode" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/math-mode" nil nil)
		       ("mbq" "\\mathbf{${1:x}}$0" "math-bold" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/math-bold" nil nil)
		       ("map" "\\mapsto" "mapsto" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/mapsto" nil nil)
		       ("mag" "\\vec{B}" "magnetic field" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/magnetic_enm" nil nil)
		       ("lim" "\\lim\\limits_{${1:n} \\rightarrow ${2:\\infty}} $0" "limit" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/limit" nil nil)
		       ("leq" "\\leq" "leq" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/leq" nil nil)
		       ("larr" "\\leftarrow" "left-arrow" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/left-arrow" nil nil)
		       ("lbf" "#+caption: ${1:Caption} \\label{fig:${2:x}}" "label-figure" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/label-figure" nil nil)
		       ("lbe" "\\label{eq:${1:x}}$0" "label-equation" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/label-equation" nil nil)
		       ("ipy" "#+BEGIN_SRC ipython :session mysession :exports both :results output code :async\n$0\n#+END_SRC" "ipython-src-code" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/ipython-src-code" nil nil)
		       ("Int" "\\int\\limits_{${3:0}}^{${4:\\infty}} ${1:f(x)} d${2:x} $0" "integral" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/integral" nil nil)
		       ("inf" "\\infty" "infinity" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/infinity" nil nil)
		       ("xu" "${1:x}^{${2:\\mu}}$0" "index_upper" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/index_upper" nil nil)
		       ("xl" "${1:x}_{${2:\\mu}}$0" "index_lower" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/index_lower" nil nil)
		       ("imp" "\\implies" "implies" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/implies" nil nil)
		       ("line" "\\noindent\\rule[0.5ex]{\\linewidth}{1pt}" "line" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/horizontal-line" nil nil)
		       ("hb" "\\hbar$0" "hbar" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/hbar" nil nil)
		       ("hat" "\\hat{${1:x}}$0" "hat" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/hat" nil nil)
		       ("half" "\\frac{1}{2}" "half" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/half" nil nil)
		       ("act" "\\cdot_{$1}$0" "group-action" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/group-action" nil nil)
		       ("gr" "\\nabla $0" "gradient" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/gradient" nil nil)
		       ("grad" "\\vec{\\nabla}" "grad" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/grad_enm" nil nil)
		       ("geq" "\\geq" "geq" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/geq" nil nil)
		       ("bbb" "\\left( $1 \\right)$0" "full-brackets" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/full-brackets" nil nil)
		       ("frac" "\\frac{${1:x}}{${2:y}}$0" "fraction" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/fractions" nil nil)
		       ("frsq" "\\frac{1}{\\sqrt{2}}" "frac-sqrt2" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/frac-sqrt2" nil nil)
		       ("fa" "~~\\forall $0" "forall" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/forall" nil nil)
		       ("floor" "\\lfloor ${1:x} \\rfloor$0" "floor" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/floor" nil nil)
		       ("exp" "\\exp \\left[ ${1:x} \\right] $0" "exponential" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/exponential" nil nil)
		       ("ex" "\\exists &0\n" "exists" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/exists" nil nil)
		       ("eqv" "\\equiv" "equivalent" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/equivalent" nil nil)
		       ("ee" "\\[ $1 \\]$0" "equation-unnumbered" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/equation-unnumbered" nil nil)
		       ("ea" "\\begin{align} \n${1:y = mx +c}\n\\end{align}\n$0" "equation-aligned" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/equation-aligned" nil nil)
		       ("emp" "\\emptyset" "empty-set" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/empty-set" nil nil)
		       ("ele" "\\vec{E}" "electric field" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/electric_enm" nil nil)
		       ("Arr" "\\Rightarrow" "double-right-arrow" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/double-right-arrow" nil nil)
		       ("pd2" "\\frac{\\partial^2 ${1:num} }{\\partial ${2:den}^2 }$0" "double-partial-derivative" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/double-partial-derivative" nil nil)
		       ("mod2" "\\left\\lVert ${1:x} \\right\\rVert$0" "double-mod" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/double-mod" nil nil)
		       ("Larr" "\\Leftarrow" "double-left-arrow" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/double-left-arrow" nil nil)
		       ("div" "\\vec{\\nabla} \\cdot " "divergence" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/div" nil nil)
		       ("dp" "\\oplus $0" "direct-product" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/direct-product" nil nil)
		       ("d2" "\\frac{d^2 ${1:num}}{d {${2:den}^2} $0" "derivative-second" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/derivative-second" nil nil)
		       ("pde" "\\frac{\\partial ${1:x}}{\\partial ${2:y}}$0" "derivative partial" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/derivative partial" nil nil)
		       ("dd" "\\frac{d ${1:num}}{d ${2:den}}$0" "derivative" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/derivative" nil nil)
		       ("del" "\\nabla" "del" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/del" nil nil)
		       ("circ" "\\circ" "circ" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/deg" nil nil)
		       ("{}" "\\left{ $1 \\right}$0" "curly_brackets" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/curly_brackets" nil nil)
		       ("cc" "{ ${1:x} }$0 " "curly-brackets" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/curly-brackets" nil nil)
		       ("curl" "\\vec{\\nabla} \\times " "curl" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/curl_enm" nil nil)
		       ("cos" "\\cos \\left( $1 \\right)$0" "cosine" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/cosine" nil nil)
		       ("con" "\\overline{${1:z}}$0" "conjuate" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/conjugate" nil nil)
		       ("ceil" "\\lceil ${1:x} \\rceil$0" "ceil" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/ceil" nil nil)
		       ("dot" "\\cdot" "cdot" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/cdot" nil nil)
		       ("()" "\\left( ${1:x} \\right)$0" "brackets" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/brackets" nil nil)
		       ("bd" "\\mathbf{$1} \\cdot \\mathbf{$2}$0" "bold vector dot product" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/bold vector dot product" nil nil)
		       ("begin" "\\begin{$1}\n$2\n\\end{$1}\n$0" "begin-code" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/begin-code" nil nil)
		       ("|" "~|~" "bar" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/bar_horizontal" nil nil)
		       ("ax" "[$$] $1 [/$$]\n$0" "anki" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/anki" nil nil)
		       ("angstrom" "\\text{\\normalfont\\AA}" "angstrom" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/angstrom" nil nil)
		       ("aa" "\\begin{align}\n  ${1:x=y}\n\\end{align}\n$0" "aligned_equations" nil nil nil "/Users/bibekpokharel/Dropbox/emacs_init_new/snippets/math-mode/aligned_equations" nil nil)))


;;; Do not edit! File generated at Tue Jul 16 17:51:18 2019
